[package]
name = "calc_builder"
version = "0.1.0"
authors = ["Aldey Wahyu Putra"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photo_kaonstar = { path = "../../calc" }